##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Thu May 23 14:19:04 CEST 2024] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# FLASH VIA CANBUS CAN-ids of devices
######################################
SENS_FRONT__CANID_XCP_HOST_TO_TARGET__HEX=00A
SENS_FRONT__CANID_XCP_TARGET_TO_HOST__HEX=184

SENS_REAR__CANID_XCP_HOST_TO_TARGET__HEX=00B
SENS_REAR__CANID_XCP_TARGET_TO_HOST__HEX=185

######################################
# target
######################################
TARGET = sensorboard


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/adc.c \
Core/Src/bsp.c \
Core/Src/can.c \
Core/Src/can_send_timebase.c \
Core/Src/can_utils.c \
Core/Src/data_reading_timebase.c \
Core/Src/dma.c \
Core/Src/gpio.c \
Core/Src/gpio_sensing.c \
Core/Src/iwdg.c \
Core/Src/logger_wrapper.c \
Core/Src/main.c \
Core/Src/sc22_evo_canlv.c \
Core/Src/spi.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/system_stm32f4xx.c \
Core/Src/tim.c \
Core/Src/usart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_adc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_can.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_iwdg.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_adc.c \
Lib/SCan/SC22EVO/artifacts/MCB/c_source/mcb.c \
Lib/adc1283/adc1283.c \
Lib/stmlibs/circular_buffer/circular_buffer.c \
Lib/stmlibs/error_utils/error_utils.c \
Lib/stmlibs/fsm/fsm.c \
Lib/stmlibs/logger/logger.c \
Lib/stmlibs/longcounter/longcounter.c \
Lib/stmlibs/pwm/pwm.c \
Lib/stmlibs/timebase/timebase.c \
Lib/stmlibs/timer_utils/timer_utils.c

CPP_SOURCES = \


# ASM sources
ASM_SOURCES =  \
startup_stm32f446xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32F446xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-ILib/SCan/SC22EVO/artifacts/MCB/c_source \
-ILib/adc1283 \
-ILib/stmlibs \
-ILib/stmlibs/circular_buffer \
-ILib/stmlibs/critical_section \
-ILib/stmlibs/error_utils \
-ILib/stmlibs/fsm \
-ILib/stmlibs/lock \
-ILib/stmlibs/logger \
-ILib/stmlibs/longcounter \
-ILib/stmlibs/pwm \
-ILib/stmlibs/timebase \
-ILib/stmlibs/timer_utils


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -fstack-usage

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -fstack-usage

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -specs=nano.specs -u _printf_float

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@

#######################################
# custom makefile rules
#######################################

# The openocd bin path can be either defined in make command via OPENOCD_PATH variable (> make OPENOCD_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef OPENOCD_PATH
OPENOCD = "$(OPENOCD_PATH)/openocd"
else
OPENOCD = "openocd"
endif
#######################################
# flash
#######################################
flash: openocd.cfg $(BUILD_DIR)/$(TARGET).elf
	$(OPENOCD) -f ./openocd.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: openocd.cfg $(BUILD_DIR)/$(TARGET).elf
	$(OPENOCD) -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)


#######################################
# can_build
#######################################
can_build: $(BUILD_DIR)/$(TARGET)_shifted.sx
	

# The openocd bin path can be either defined in make command via BIN2SREC_PATH variable (> make BIN2SREC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef BIN2SREC_PATH
BIN2SREC = "$(BIN2SREC_PATH)/bin2srec"
else
BIN2SREC = "bin2srec"
endif
#######################################
# $(BUILD_DIR)/$(TARGET)_shifted.sx
#######################################
$(BUILD_DIR)/$(TARGET)_shifted.sx: $(BUILD_DIR)/$(TARGET)_shifted.bin
	$(BIN2SREC) -a $$(grep 'FLASH (rx)      : ORIGIN =' STM32F446RETx_FLASH_shifted.ld | awk '{print $$6}' | sed 's/.$$//') -i $(BUILD_DIR)/$(TARGET)_shifted.bin -o $(BUILD_DIR)/$(TARGET)_shifted.sx
      

#######################################
# $(BUILD_DIR)/$(TARGET)_shifted.elf
#######################################
$(BUILD_DIR)/$(TARGET)_shifted.elf: $(OBJECTS) STM32Make.make
	$(CC) $(OBJECTS) $(MCU) $(ADDITIONALLDFLAGS) -TSTM32F446RETx_FLASH_shifted.ld $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -o $@


#######################################
# $(BUILD_DIR)/$(TARGET)_shifted.bin
#######################################
$(BUILD_DIR)/$(TARGET)_shifted.bin: $(BUILD_DIR)/$(TARGET)_shifted.elf | $(BUILD_DIR)
	$(BIN) $< $@

# The openocd bin path can be either defined in make command via BOOTCOMMANDER_PATH variable (> make BOOTCOMMANDER_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef BOOTCOMMANDER_PATH
BOOTCOMMANDER = "$(BOOTCOMMANDER_PATH)/BootCommander"
else
BOOTCOMMANDER = "BootCommander"
endif
#######################################
# can_flash_front
#######################################
can_flash_front: $(BUILD_DIR)/$(TARGET)_shifted.sx
	$(BOOTCOMMANDER) -t=xcp_can -d=can0 -b=1000000 -tid="$(SENS_FRONT__CANID_XCP_HOST_TO_TARGET__HEX)h" -rid="$(SENS_FRONT__CANID_XCP_TARGET_TO_HOST__HEX)h" $(BUILD_DIR)/$(TARGET)_shifted.sx


#######################################
# can_flash_rear
#######################################
can_flash_rear: $(BUILD_DIR)/$(TARGET)_shifted.sx
	$(BOOTCOMMANDER) -t=xcp_can -d=can0 -b=1000000 -tid="$(SENS_REAR__CANID_XCP_HOST_TO_TARGET__HEX)h" -rid="$(SENS_REAR__CANID_XCP_TARGET_TO_HOST__HEX)h" $(BUILD_DIR)/$(TARGET)_shifted.sx
      
	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
