#ifndef UTILS_H
#define UTILS_H

#include "main.h"

#define SENS_TYPE_FRONT    GPIO_PIN_RESET
#define SENS_TYPE_REAR     GPIO_PIN_SET

#define MCB_DIAG_TOOL_XCP_TX_SB_FRONT_FRAME_ID  (0x2b6)
#define MCB_DIAG_TOOL_XCP_TX_SB_REAR_FRAME_ID   (0x2a6)

#define MCB_SB_FRONT_XCP_TX_FRAME_ID            (0x462u)
#define MCB_SB_REAR_XCP_TX_FRAME_ID             (0x463u)

#define BSP_RX_XCP_MSG_ID (HAL_GPIO_ReadPin(SENSE_TYPE_GPIO_Port, SENSE_TYPE_Pin) == SENS_TYPE_FRONT ? MCB_DIAG_TOOL_XCP_TX_SB_FRONT_FRAME_ID : MCB_DIAG_TOOL_XCP_TX_SB_REAR_FRAME_ID)
#define BSP_TX_XCP_MSG_ID (HAL_GPIO_ReadPin(SENSE_TYPE_GPIO_Port, SENSE_TYPE_Pin) == SENS_TYPE_FRONT ? MCB_SB_FRONT_XCP_TX_FRAME_ID : MCB_SB_REAR_XCP_TX_FRAME_ID)

#endif // UTILS_H