#ifndef UTILS_H
#define UTILS_H

#include "main.h"

#define SENS_TYPE_FRONT    GPIO_PIN_RESET
#define SENS_TYPE_REAR     GPIO_PIN_SET

#define BSP_RX_XCP_MSG_ID (HAL_GPIO_ReadPin(SENSE_TYPE_GPIO_Port, SENSE_TYPE_Pin) == SENS_TYPE_FRONT ? SENS_FRONT__CANID_XCP_HOST_TO_TARGET__HEX : SENS_REAR__CANID_XCP_HOST_TO_TARGET__HEX)
#define BSP_TX_XCP_MSG_ID (HAL_GPIO_ReadPin(SENSE_TYPE_GPIO_Port, SENSE_TYPE_Pin) == SENS_TYPE_FRONT ? SENS_FRONT__CANID_XCP_TARGET_TO_HOST__HEX : SENS_REAR__CANID_XCP_TARGET_TO_HOST__HEX)

#endif // UTILS_H
